services:
  db:
    image: postgres:16
    container_name: moodtune_db
    restart: always
    environment:
      POSTGRES_USER: moodtune
      POSTGRES_PASSWORD: moodtune123
      POSTGRES_DB: moodtunedb
    ports:
      - "5433:5432"
    volumes:
      - moodtune_db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: moodtune_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - moodtune_rabbitmq_data:/var/lib/rabbitmq

volumes:
  moodtune_db_data:
  moodtune_rabbitmq_data: